services:
  - type: web
    name: omnipull
    runtime: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: omnipull-redis
          property: connectionString
      - key: PORT
        value: 8000
      - key: TMP_DIR
        value: /tmp/omnipull

  - type: redis
    name: omnipull-redis
    plan: free
    ipAllowList: []
